sudo: required
services:
  - docker

before_install:
  - docker build -t chrisosfp/react-test -f ./client/Dockerfile.dev ./client 


script:
  - docker run -e CI=true chrisosfp/react-test npm test -- --coverage

after_success:
  - docker build -t chrisosfp/multi-client ./client 
  - docker build -t chrisosfp/multi-nginx  ./nginx
  - docker build -t chrisosfp/multi-server ./server
  - docker build -t chrisosfp/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push chrisosfp/multi-client
  - docker push chrisosfp/multi-nginx
  - docker push chrisosfp/multi-server
  - docker push chrisosfp/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-951913066313"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY